### ISSUE TITLE
Mod doesnt work at all

### ISSUE THREAD

**Issue by subzerohurley** [Qlevine/DeadAndBored#2]
As the title says, the mod simply does not work

**Comment by Qlevine** [comment]
Hmm hard to know exactly what the issue is. I just tested myself and it worked. Make sure you are pressing the "Talk" key (default is Y). Also if you are using Push to Talk, then you might need to press both the Push to Talk key and the "Talk" key. If its still not working, would you mind sending me a modpack? Could be a different mod is interfering with it. Thanks

**Comment by VanilaBOI** [comment]
It could be that you need to press z because for europen key boards it's switched but the mod/game doesn't see that difference.
